# Use the following code for the questions below:

In [6]:
import numpy as np

In [5]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

# 1A. How many negative numbers are there?

In [9]:
#loops through the list to add only neg numbers to the new list
negative_numbers = [num for num in a if num < 0]
print("There are " + str(len(negative_numbers)) + " negative numbers.")

#using numpy
print("There are " + str((a < 0).sum()) + " negative numbers.")

There are 4 negative numbers.
There are 4 negative numbers.


# 2A. How many positive numbers are there?

In [11]:
#loops through the list to add only positive numbers to the new list
positive_numbers = [num for num in a if num > 0]
print("There are " + str(len(positive_numbers)) + " positive numbers.")

#using numpy
print("There are " + str((a > 0).sum()) + " positive numbers.")

There are 5 positive numbers.
There are 5 positive numbers.


# 3A. How many even positive numbers are there?

In [13]:
#loops through the list to add only even positive numbers to the new list
positive_even_numbers = [num for num in a if num > 0 and num % 2 == 0]
print("There are " + str(len(positive_even_numbers)) + " positive even numbers.")

#using numpy
print("There are " + str(((a > 0) & (a % 2 == 0)).sum()) + " positive even numbers.")

There are 3 positive even numbers.
There are 3 positive even numbers.


# 4A. If you were to add 3 to each data point, how many positive numbers would there be?

In [14]:
#loops to add 3 to each number in a
plus_num = [num + 3 for num in a]

#loops to add positive numbers from the plus_num
plus_positive_numbers = [num for num in plus_num if num > 0]
print("There are " + str(len(plus_positive_numbers)) + " positive even numbers if you add 3.")

#using numpy
b = a + 3
print("There are " + str((b > 0).sum()) + " positive even numbers if you add 3.")

There are 10 positive even numbers if you add 3.
There are 10 positive even numbers if you add 3.


# 5A. If you squared each number, what would the new mean and standard deviation be?

In [15]:
#if not using numpy, you can import statistics for std
import statistics

#average is calculated by sum of a divided by total items in a
mean_of_a = sum(a) / len(a)
mean_of_a_sqr = mean_of_a ** 2

#avg and std are calculated for both the original array and the squared array
std_of_a = statistics.stdev(a)
std_of_a_sqr = std_of_a ** 2

#using numpy
#we do not have to import statistics
mean = np.average(a)
#numpy has a stddeviation function
standdev = np.std(a)
print("The average of a is: " + str(mean))
print("The standard deviation of a is: " + str(standdev))

#we can square the series with numoy and use the avg and std functions
b = a ** 2
squared_mean = np.average(b)
squared_std = np.std(b)
print("The average of a squared is: " + str(squared_mean))
print("The standard deviation of a squared is: " + str(squared_std))

The average of a is: 3.0
The standard deviation of a is: 8.06225774829855
The average of a squared is: 74.0
The standard deviation of a squared is: 144.0243035046516


# 6A. A common statistical operation on a dataset is centering. This means to adjust the data such that the center of the data is at 0. This is done by subtracting the mean from each data point. Center the data set.

In [44]:
#loops through the list subtracting the mean calculated earlier without numpy
a_center = [(n - int(mean_of_a)) for n in a]

#using numpy
a_centered = a - int(mean)
print(a_centered)

[1, 7, 9, 20, -5, -4, -3, -3, -3, -9, 0, -10]
[  1   7   9  20  -5  -4  -3  -3  -3  -9   0 -10]


# 7A. Calculate the z-score for each data point. Recall that the z-score is given by:

Z = x − μσ

In [23]:
#z score is (number - average) / standard deviation
a_z_score = (a - mean) / int(standdev)
print(a_z_score)

#using function
from scipy import stats
print(stats.zscore(a, axis = 0))

[ 0.125  0.875  1.125  2.5   -0.625 -0.5   -0.375 -0.375 -0.375 -1.125
  0.    -1.25 ]
[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


# 8A. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

# Setup 1

In [24]:
import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:

# 1B. Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [25]:
#we use sum because one list, not multidimensional
sum_of_a = sum(a)
print(sum_of_a)

55


# 2B - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [26]:
#we use min because one list, not multidimensional
min_of_a = min(a)
print(min_of_a)

1


# 3B. Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [27]:
#we use max because one list, not multidimensional
max_of_a = max(a)
print(max_of_a)

10


# 4B. Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [30]:
#we use sum and len because one list, not multidimensional
mean_of_a = sum_of_a / len(a)
print(mean_of_a)

5.5


# 5B. Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [31]:
#we must loop through each item in n, multiplying by sount variable to hold this total
count = 1
for num in a:
    count *= num
count

3628800

# 6B. Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [38]:
#we loop through each item in a
squares_of_a = []
for n in a:
    #we add the new value to an empty list
    squared = n ** 2
    squares_of_a.append(squared)
    
print(squares_of_a)

#using list comprehension
squares_of_a2 = [n ** 2 for n in a]
print(squares_of_a2)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


# 7B. Make a variable named odds_in_a. It should hold only the odd numbers

In [36]:
#makes an empty list to append the odd numbers too
odds_in_a = []
#loops through each number in a
for n in a:
    #if odd it adds to the list
    if n % 2 != 0:
        odds_in_a.append(n)
    
print(odds_in_a)

#using list comprehension, equivalent to above
odds_in_a2 = [n for n in a if n % 2 != 0]
print(odds_in_a2)

[1, 3, 5, 7, 9]
[1, 3, 5, 7, 9]


# 8B. Make a variable named evens_in_a. It should hold only the evens.

In [40]:
#using list comprehension
#loops through each number and if even it adds to the variable
evens_in_a = [n for n in a if n % 2 == 0]
print(evens_in_a)

[2, 4, 6, 8, 10]


## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [2]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [50]:
#sum
#set an empty varialbe to add to
total = 0
#loops through the list of lists
for lists in b:
    #adds to the total for each number in the lists
    total += sum(lists)
print(total)

33


In [53]:
#min
#sets the min to the first value in the list of lists, index 0 of list 0
min_b = b[0][0]
#loops through the 2 lists in the list of lists
for lists in b:
    #checks min of list, if less it becomes the new min
    if min_b > min(lists):
        min_b = min(lists)
print(min_b)

3


In [55]:
#max
#sets max to the the first value in the list of lists, index 0 of list 0
max_b = b[0][0]
#loops through the 2 lists in the list of lists
for lists in b:
    #checks max of list, if more it becomes the new max
    if max_b < max(lists):
        max_b = max(lists)
print(max_b)

8


In [57]:
#average
#sets empty total for the sum of the list of lists
total = 0
#sets empty count for the items in the list of lists
count = 0
#loops through each item in the lists to add to the sum and total
for lists in b:
    total += sum(lists)
    count += len(lists)
#average = total/count
print(total/count)

5.5


In [58]:
#product
#this time we set the 'empty' varialbe to one, because if we multiply by 0 it would remain 0
total = 1
#loops through the lists in the list
for lists in b:
    #loops through the numbers in the list
    for nums in lists:
        #multiplys the numbers by the list
        total *= nums
print(total)

20160


In [4]:
#list of squares
#makes a new list with the same values as b
b_squared = b

#loops throught the lists in the list
for lists in b_squared:
    #sets count to 0 for each list in the list
    #how we index the item in the individual lists
    count = 0
    #loops through the numbers in the list
    for nums in lists:
        #the value of the number is squared
        lists[count] = nums ** 2
        count += 1

print(b_squared)

[[9, 16, 25], [36, 49, 64]]


# 1C. Refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**

In [15]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
])

In [6]:
#without numpy
sum_of_b1 = 0
for row in b:
    sum_of_b += sum(row)

#np.sum() calculates the sum without us having to loop through the items
sum_of_b2 = np.sum(b)
print(sum_of_b2)

33


# 2C. Refactor the following to use numpy. 

In [8]:
#without numpy
min_of_b1 = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

#np.min() calculates the sum without us having to create conditionals and loops
min_of_b2 = np.min(b)
print(min_of_b2)

3


# 3C. Refactor the following maximum calculation to find the answer with numpy.

In [10]:
#without numpy
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

#np.max() calculates the max without us having to use conditionals and loops
max_of_b2 = np.max(b)
print(max_of_b2)

8


# 4C. Refactor the following using numpy to find the mean of b

In [13]:
#without numpy
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

#np.mean() calculates the average without having to find the sum and then divide by the total items
avg_of_b = np.mean(b)
print(avg_of_b)

5.5


# 5C. Refactor the following to use numpy for calculating the product of all numbers multiplied together.

In [16]:
#without numpy
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

#np.product() multiplies all the items together without having to loop through each item in items
product = np.product(b)
print(product)

20160
20160


# 6C. Refactor the following to use numpy to find the list of squares 

In [8]:
#without numpy
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

#np.square() returns the items of all squared without having to loop
squares = np.square(b)
print(squares)

[[ 9 16 25]
 [36 49 64]]


# 7C. Refactor using numpy to determine the odds_in_b

In [16]:
#without numpy
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

#we can create a conditional, and numpy will apply it to each item without us using loops
#this checks if the items are odd, and encasing in b[] will show us each item in b that returns true
odds = b[b % 2 != 0]
print(odds)

[3 5 7]


# 8C. Refactor the following to use numpy to filter only the even numbers

In [18]:
#without numpy
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

#we can create a conditional, and numpy will apply it to each item without loops
#this checks if the items are even, and encasing in b[] shows us each item that returns True
evens = b[b % 2 == 0]
print(evens)

[4 6 8]


# 9C. Print out the shape of the array b.

In [19]:
#np.shape() shows the total number of items and how many items are in each
print(np.shape(b))

(2, 3)


# 10C. Transpose the array b.

In [20]:
#np.transpose switches the shape, so a 2x3 matrix would become a 3x2 matrix
#the rows become the columns and vice verse
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

# 11C. Reshape the array b to be a single list of 6 numbers. (1 x 6)

In [21]:
#reshape() allows us to pick a new shape the numbers should become
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

# 12C. Reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [22]:
#rehape(rows, columns)
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

## Setup 3

In [8]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

# 1D. Find the min, max, sum, and product of c.

In [27]:
#min
c_min = np.min(c)
#max
c_max = np.max(c)
#sum
c_sum = np.sum(c)
#product
c_prod = np.product(c)

print(c_min, c_max, c_sum, c_prod)

1 9 45 362880


# 2D. Determine the standard deviation of c.

In [47]:
#using numpy function for stddev
stddev = np.std(c)
print(stddev)

2.581988897471611


# 3D. Determine the variance of c.

In [48]:
#using variance function of numpy
variance = np.var(c)
print(variance)

6.666666666666667


# 4D. Print out the shape of the array c

In [49]:
#using shape function of numpy
print(np.shape(c))

(3, 3)


# 5D. Transpose c and print out transposed result.

In [50]:
#using transpose function of numpy
print(np.transpose(c))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# 6D. Get the dot product of the array c with c. 

In [51]:
#np.dot(object, object) multiplies two arrays or matrices together, i.e. the dot product
print(np.dot(c,c))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


# 7D. Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [9]:
#we take the sum of c multiplied by c transposed
c_trans_sum = np.sum(c * np.transpose(c))
print(c_trans_sum)

261


# 8D. Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [95]:
#we take the product of c times c transposed
product = np.product(c * np.transpose(c))
print(product)

131681894400


In [67]:
## Setup 4
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
])

# 1E. Find the sine of all the numbers in d

In [69]:
#using numpy sine function
print(np.sin(d))

[[ 0.89399666 -0.98803162  0.85090352  0.          0.58061118 -0.80115264]
 [ 0.85090352 -0.89399666  0.98803162 -0.17604595  0.89399666  0.        ]
 [-0.30481062  0.85090352 -0.85090352  0.89399666 -0.85090352 -0.80115264]]


# 2E. Find the cosine of all the numbers in d

In [70]:
#using numpy cosine function
print(np.cos(d))

[[-0.44807362  0.15425145  0.52532199  1.          0.81418097 -0.59846007]
 [ 0.52532199 -0.44807362  0.15425145  0.98438195 -0.44807362  1.        ]
 [-0.95241298  0.52532199  0.52532199 -0.44807362  0.52532199 -0.59846007]]


# 3E. Find the tangent of all the numbers in d

In [71]:
#using numpy tangent function
print(np.tan(d))

[[-1.99520041 -6.4053312   1.61977519  0.          0.71312301  1.33869021]
 [ 1.61977519  1.99520041  6.4053312  -0.17883906 -1.99520041  0.        ]
 [ 0.32004039  1.61977519 -1.61977519 -1.99520041 -1.61977519  1.33869021]]


# 4E. Find all the negative numbers in d

In [72]:
#use conditional to find all negative numbers
print(d[d < 0])

[-90 -30 -45 -45]


# 5E. Find all the positive numbers in d

In [73]:
#creates a subseries of all values in d greater than 0
print(d[d > 0])

[ 90  30  45 120 180  45 270  90  60  45  90 180]


# 6E. Return an array of only the unique numbers in d.

In [74]:
#returns all numbers without repeats
print(np.unique(d))

[-90 -45 -30   0  30  45  60  90 120 180 270]


# 7E. Determine how many unique numbers there are in d.

In [87]:
#counts the number of distinct numbers
(np.unique(d)).size

11

# 8E. Print out the shape of d.

In [88]:
#shape gives the rows and columns of the series
np.shape(d)

(3, 6)

# 9E. Transpose and then print out the shape of d.

In [90]:
np.shape(np.transpose(d))

(6, 3)

# 10E. Reshape d into an array of 9 x 2

In [91]:
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])

# 9. For even more practice, clone https://github.com/rougier/numpy-100, make your own repo called numpy-100, and then commit and push your solutions to your own repo.