# Use the following code for the questions below:

In [2]:
import numpy as np

In [31]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

# 1A. How many negative numbers are there?

In [99]:
negative_numbers = [num < 0 for num in a]
a[negative_numbers]
print("There are " + str(len(a[negative_numbers])) + " negative numbers.")

#using numpy
print("There are " + str((a < 0).sum()) + " negative numbers.")

There are 4 negative numbers.
There are 4 negative numbers.


# 2A. How many positive numbers are there?

In [102]:
positive_numbers = [num > 0 for num in a]
a[positive_numbers]
print("There are " + str(len(a[positive_numbers])) + " positive numbers.")

#using numpy
print("There are " + str((a > 0).sum()) + " positive numbers.")

There are 5 positive numbers.
There are 5 positive numbers.


# 3A. How many even positive numbers are there?

In [111]:
positive_even_numbers = [num > 0 and num % 2 == 0 for num in a]
a[positive_even_numbers]
print("There are " + str(len(a[positive_even_numbers])) + " positive even numbers.")

#using numpy
print("There are " + str(((a > 0) & (a % 2 == 0)).sum()) + " positive even numbers.")

There are 3 positive even numbers.
There are 3 positive even numbers.


# 4A. If you were to add 3 to each data point, how many positive numbers would there be?

In [8]:
b = a + 3

plus_positive_numbers = [num > 0 for num in b]
print("There are " + str(len(b[plus_positive_numbers])) + " positive even numbers if you add 3.")

#using numpy
print("There are " + str((b > 0).sum()) + " positive even numbers if you add 3.")

There are 10 positive even numbers if you add 3.
There are 10 positive even numbers if you add 3.


# 5A. If you squared each number, what would the new mean and standard deviation be?

In [40]:
import statistics
mean_of_a = sum(a) / len(a)
mean_of_a_sqr = mean_of_a ** 2

std_of_a = statistics.stdev(a)
std_of_a_sqr = std_of_a ** 2

#using numpy
mean = np.average(a)
standdev = np.std(a)
print("The average of a is: " + str(mean))
print("The standard deviation of a is: " + str(standdev))

b = a ** 2
squared_mean = np.average(b)
squared_std = np.std(b)
print("The average of a squared is: " + str(squared_mean))
print("The standard deviation of a squared is: " + str(squared_std))

The average of a is: 3.0
The standard deviation of a is: 8.06225774829855
The average of a squared is: 74.0
The standard deviation of a squared is: 144.0243035046516


# 6A. A common statistical operation on a dataset is centering. This means to adjust the data such that the center of the data is at 0. This is done by subtracting the mean from each data point. Center the data set.

In [44]:
a_center = [(n - int(mean_of_a)) for n in a]

#using numpy
a_centered = a - int(mean)
print(a_centered)

[1, 7, 9, 20, -5, -4, -3, -3, -3, -9, 0, -10]
[  1   7   9  20  -5  -4  -3  -3  -3  -9   0 -10]


# 7A. Calculate the z-score for each data point. Recall that the z-score is given by:

Z = x − μσ

In [23]:
a_z_score = (a - mean) / int(standdev)
print(a_z_score)

#using function
from scipy import stats
print(stats.zscore(a, axis = 0))

[ 0.125  0.875  1.125  2.5   -0.625 -0.5   -0.375 -0.375 -0.375 -1.125
  0.    -1.25 ]
[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


# 8A. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

# Setup 1

In [24]:
import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:

# 1B. Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [25]:
sum_of_a = sum(a)
print(sum_of_a)

55


# 2B - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [26]:
min_of_a = min(a)
print(min_of_a)

1


# 3B. Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [27]:
max_of_a = max(a)
print(max_of_a)

10


# 4B. Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [30]:
mean_of_a = sum_of_a / len(a)
print(mean_of_a)

5.5


# 5B. Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [31]:
count = 1
for num in a:
    count *= num
count

3628800

# 6B. Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [38]:
squares_of_a = []
for n in a:
    squared = n ** 2
    squares_of_a.append(squared)
    
print(squares_of_a)

squares_of_a2 = [n ** 2 for n in a]
print(squares_of_a2)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


# 7B. Make a variable named odds_in_a. It should hold only the odd numbers

In [36]:
odds_in_a = []
for n in a:
    if n % 2 != 0:
        odds_in_a.append(n)
    
print(odds_in_a)

odds_in_a2 = [n for n in a if n % 2 != 0]
print(odds_in_a2)

[1, 3, 5, 7, 9]
[1, 3, 5, 7, 9]


# 8B. Make a variable named evens_in_a. It should hold only the evens.

In [40]:
evens_in_a = [n for n in a if n % 2 == 0]
print(evens_in_a)

[2, 4, 6, 8, 10]


## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [5]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [50]:
#sum
total = 0
for lists in b:
    total += sum(lists)
print(total)

33


In [53]:
#min
min_b = b[0][0]
for lists in b:
    if min_b > min(lists):
        min_b = min(lists)
print(min_b)

3


In [55]:
#max
max_b = b[0][0]
for lists in b:
    if max_b < max(lists):
        max_b = max(lists)
print(max_b)

8


In [57]:
#average
total = 0
count = 0
for lists in b:
    total += sum(lists)
    count += len(lists)
print(total/count)

5.5


In [58]:
#product
total = 1
for lists in b:
    for nums in lists:
        total *= nums
print(total)

20160


In [2]:
#list of squares
b_squared = b

for lists in b_squared:
    count = 0
    for nums in lists:
        lists[count] = nums ** 2
        count += 1

print(b_squared)

[[9, 16, 25], [36, 49, 64]]


# 1C. Refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**

In [15]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
])

In [6]:
sum_of_b1 = 0
for row in b:
    sum_of_b += sum(row)

sum_of_b2 = np.sum(b)
print(sum_of_b2)

33


# 2C. Refactor the following to use numpy. 

In [8]:
min_of_b1 = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

min_of_b2 = np.min(b)
print(min_of_b2)

3


# 3C. Refactor the following maximum calculation to find the answer with numpy.

In [10]:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

max_of_b2 = np.max(b)
print(max_of_b2)

8


# 4C. Refactor the following using numpy to find the mean of b

In [13]:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

avg_of_b = np.mean(b)
print(avg_of_b)

5.5


# 5C. Refactor the following to use numpy for calculating the product of all numbers multiplied together.

In [16]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
        
product = np.product(b)
print(product)

20160
20160


# 6C. Refactor the following to use numpy to find the list of squares 

In [8]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
        
squares = np.square(b)
print(squares)

[[ 9 16 25]
 [36 49 64]]


# 7C. Refactor using numpy to determine the odds_in_b

In [16]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
            
odds = b[b % 2 != 0]
print(odds)

[3 5 7]


# 8C. Refactor the following to use numpy to filter only the even numbers

In [18]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

evens = b[b % 2 == 0]
print(evens)

[4 6 8]


# 9C. Print out the shape of the array b.

In [19]:
print(np.shape(b))

(2, 3)


# 10C. Transpose the array b.

In [20]:
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

# 11C. Reshape the array b to be a single list of 6 numbers. (1 x 6)

In [21]:
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

# 12C. Reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [22]:
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

## Setup 3

In [23]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

# Exercise 1 - Find the min, max, sum, and product of c.

In [27]:
#min
c_min = np.min(c)
#max
c_max = np.max(c)
#sum
c_sum = np.sum(c)
#product
c_prod = np.product(c)

print(c_min, c_max, c_sum, c_prod)

1 9 45 362880


In [ ]:
# Exercise 2 - Determine the standard deviation of c.


In [ ]:
# Exercise 3 - Determine the variance of c.

In [ ]:
# Exercise 4 - Print out the shape of the array c

In [ ]:
# Exercise 5 - Transpose c and print out transposed result.

In [ ]:
# Exercise 6 - Get the dot product of the array c with c. 

In [ ]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [ ]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [ ]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

# Exercise 1 - Find the sine of all the numbers in d

# Exercise 2 - Find the cosine of all the numbers in d

# Exercise 3 - Find the tangent of all the numbers in d

# Exercise 4 - Find all the negative numbers in d

# Exercise 5 - Find all the positive numbers in d

# Exercise 6 - Return an array of only the unique numbers in d.

# Exercise 7 - Determine how many unique numbers there are in d.

# Exercise 8 - Print out the shape of d.

# Exercise 9 - Transpose and then print out the shape of d.

# Exercise 10 - Reshape d into an array of 9 x 2

# 9. For even more practice, clone https://github.com/rougier/numpy-100, make your own repo called numpy-100, and then commit and push your solutions to your own repo.